export interface AnalysisOutput {
  title: string;
  genre: string;
  summary: string;
  emotional_arc: string;
  main_characters: string[];
  main_locations: string[];
  key_props: string[];
  estimated_duration_seconds: number;
  suggested_boards: number;
  story_beats?: StoryBeat[]; // Audio-driven mode: pacing + duration per beat
}

export interface ProductionBible {
  visual_style: string;
  color_palette: string[];
  lighting: string;
  tone: string;
  characters: BibleCharacter[];
  locations: BibleLocation[];
  props: BibleProp[];
  continuity_rules: string[];
}

export interface BibleCharacter {
  name: string;
  description: string;
  wardrobe: string;
  distinctive_features: string;
}

export interface BibleLocation {
  name: string;
  description: string;
  atmosphere: string;
  key_elements: string[];
}

export interface BibleProp {
  name: string;
  description: string;
  importance: string;
}

// Merged: each character = 1 unified prompt (reference sheet + close-up + neutral + expressive)
export interface CharacterPrompt {
  character_name: string;
  prompt: string;
}

// Merged: each location = 1 unified prompt (wide + medium + detail)
export interface LocationPrompt {
  location_name: string;
  prompt: string;
}

export interface StoryboardBoard {
  board_number: number;
  duration: number;
  audio_duration?: number; // seconds — actual audio duration (audio-driven mode)
  story_beat: string;
  characters_used: string[];
  location_used: string;
  shots: StoryboardShot[];
  storyboard_prompt: string; // multi-panel storyboard layout prompt (grid of all shots)
}

export interface StoryboardShot {
  shot_number: number;
  shot_size: string;
  lens_feel: string;
  movement: string;
  composition: string; // LOCK / TENSION / BREAK / RESTORE
  action: string;
  emotion: string;
  dialogue_audio: string;
  start_time?: number; // seconds — audio-driven mode only
  end_time?: number; // seconds — audio-driven mode only
  master_prompt?: string; // single unified prompt for this shot (generated by pipeline or breakdown)
}

export interface SeedancePromptPerBoard {
  board_number: number;
  duration: number;
  board_prompt: string; // single unified prompt for the entire board
  negative_prompt: string;
}

export interface SeedancePromptContinuous {
  total_duration: number;
  master_prompt: string; // single unified prompt for the entire continuous scene
  negative_prompt: string;
}

// --- Audio-Driven Mode Types ---

// Parsed SRT line
export interface SRTLine {
  index: number;
  startTime: number; // seconds
  endTime: number; // seconds
  text: string;
  speaker?: 'character' | 'narrator-action' | 'narrator-commentary';
  speakerName?: string; // character name if character dialogue
}

// Grouped story beat from SRT + script analysis
export interface StoryBeat {
  beat_number: number;
  start_time: number; // seconds
  end_time: number; // seconds
  description: string;
  pacing: 'intense' | 'moderate' | 'slow';
  characters: string[];
  location: string;
  dialogue_lines: SRTLine[];
  avg_shot_duration: number; // seconds per shot based on pacing
}

export interface ConsistencyReport {
  passed: boolean;
  issues: ConsistencyIssue[];
}

export interface ConsistencyIssue {
  category: string;
  description: string;
  affected_boards: number[];
  suggestion: string;
}

// Reference images stored in extension
export interface ReferenceImage {
  name: string; // character_name or location_name
  type: 'character' | 'location';
  imageDataUrl: string; // data:image/png;base64,...
  prompt: string; // the prompt used to generate it
  isManual?: boolean; // true if manually overridden (not auto-generated)
  autoImageDataUrl?: string; // saved auto-generated image for revert
}

// Board image from storyboard generation
export interface BoardImage {
  boardNumber: number;
  imageDataUrl: string; // data:image/png;base64,...
  prompt: string;
  isManual?: boolean; // true if manually overridden (not auto-generated)
  autoImageDataUrl?: string; // saved auto-generated image for revert
}

// Shot image extracted from storyboard multi-panel image
export interface ShotImage {
  boardNumber: number;
  shotNumber: number;
  imageDataUrl: string; // data:image/png;base64,... or URL
  prompt: string; // the extract/shot prompt used
}

// Log entry for the Logs tab
export interface LogEntry {
  id: string;
  timestamp: number;
  level: 'debug' | 'info' | 'warn' | 'error';
  source: string;
  message: string;
  detail?: string;
}

// Image generation run state
export interface ImageGenState {
  phase: 'idle' | 'generating-characters' | 'generating-locations' | 'generating-boards' | 'extracting-shots' | 'downloading' | 'done' | 'error';
  currentItem: string;
  progress: number; // 0-100
  totalSteps: number;
  completedSteps: number;
  refImages: ReferenceImage[];
  boardImages: BoardImage[];
  shotImages: ShotImage[];
  errors: string[];
}